version: '3.5'

services:
  # PHP fpm
  manychat-backend:
    image: manychat-backend:latest
    restart: always
    tty: true
    working_dir: /var/www/manychat/src
    #env_file:
    # - .env
    volumes:
      - .:/var/www/manychat/
    networks:
      - manychat-network
    container_name: manychat-backend

  # Nginx Service
  manychat-nginx:
    image: nginx
    container_name: manychat-nginx
    restart: always
    tty: true
    environment:
      - APPLICATION_UPSTREAM=manychat-backend:9000
    volumes:
      - ./docker/nginx/manychat/:/etc/nginx/conf.d
      - ./docker/nginx/templates/:/etc/nginx/templates/
    networks:
      - manychat-network
    ports:
      - "80:80"
      - "443:443"
    links:
      - manychat-backend

  # MySQL Service
  manychat-mysql:
    image: library/mysql:8.0
    container_name: manychat-mysql
    restart: always
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: manychat
      MYSQL_USER: mcphp
      MYSQL_PASSWORD: phppass
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_NAME: mysql
    networks:
      - manychat-network
    volumes:
      - applicationMysqlData:/var/lib/mysql
      - applicationMysqlFiles:/var/lib/mysql-files
#Docker Networks
networks:
  manychat-network:
    driver: bridge
#Docker Volumes
volumes:
  applicationMysqlData:
    driver: local
  applicationMysqlFiles:
    driver: local